[package]
name = "dmarc_aggregate_parser"
version = "0.1.0"
authors = ["Brian Bustin <brian@bustin.us>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.3"
libflate = "0.1"